### ISSUE TITLE
Create a Google doc for meeting logs

### ISSUE THREAD

**Issue by ugurdogrusoz** [yalchinAlv/2C.Space-Invaders#2]
and make sure the instructor and the TA has read access to it. Also make sure README.md has a link to it. You will update this doc as you meet.

**Comment by yalchinAlv** [comment]
- Is it enough just to update README.md with the link, since anyone with the link can view the doc. Or should we also send the link to the instructor and TA's email addresses?

- Should we update README.md on both branches or only on unstable branch?

**Comment by ugurdogrusoz** [comment]
@yalchinAlv 
- it's enough to provide a link to the doc from the README.
- choose one (preferably master branch) and leave the other empty

**Comment by yalchinAlv** [comment]
@ugurdogrusoz 
Added a link for the Google doc for meeting logs to the README on master branch. But I could not figure out how to remove the README on unstable branch, since if I delete it, it will also be deleted from master branch when we merge them.

**Comment by ugurdogrusoz** [comment]
No need to delete the readme, just leave the one on unstable branch empty

**Comment by yalchinAlv** [comment]
@ugurdogrusoz 

Updated README on unstable branch and made README on master branch empty.
